version: 2
jobs:
  test:
    docker:
      - image: circleci/node:11.9
    working_directory: ~/src
    steps:
      - checkout
      - restore_cache:
          keys:
            - dependency-cache-{{ checksum "package.json" }}
      - run: npm install
      - save_cache:
          paths:
            - node_modules
          key: dependency-cache-{{ checksum "package.json" }}
      - run:
          name: lint
          command: yarn run lint
      - run: npm test
      - run: npm build

workflows:
  version: 2
  build-workflow:
    jobs:
      - test
