version: 2
jobs:
  build:
    docker:
      - image: circleci/node:11.9
    working_directory: ~/src
    steps:
      - checkout
      - restore_cache:
          keys:
            - dependency-cache-{{ checksum "package.json" }}
      - run: npm install
      - save_cache:
          paths:
            - node_modules
          key: dependency-cache-{{ checksum "package.json" }}
      - run:
          name: lint
          command: |
            mkdir -p /tmp/test-reports/eslint
            node_modules/.bin/eslint . --format junit --output-file /tmp/test-reports/eslint/results.xml
          store_test_results:
            path: /tmp/test-reports
      - run: npm test
      - run: npm build